Update localization.cfg
radistmorse/KSPPreciseManeuver pull request #10
Opened 2017-06-02 03:48 UTC by Deltathiago98

2017-06-04 00:49 UTC, radistmorse requested changes
Sorry it take me so long, I was busy all week.
Please, consider the changes that I suggested.

2017-06-04 00:49 UTC, radistmorse commented on Localization/localization.cfg
> +        precisemaneuver_keybindings_timex10             = Cambiar x10 veces
It means toggle x10 FOR time, means, toggle the increment being ten times bigger for UT.

2017-06-04 00:49 UTC, radistmorse commented on Localization/localization.cfg
> +        precisemaneuver_pager_delete                    = Eliminar
Can it be shortened to just "elim"?

2017-06-04 00:49 UTC, radistmorse commented on Localization/localization.cfg
> +        precisemaneuver_saver_save_as                   = Guardar como
No way I can fit that into the button. maybe use "nuevo" instead. It means more or less the same.

2017-06-04 00:49 UTC, radistmorse commented on Localization/localization.cfg
> +        precisemaneuver_saver_delete                    = Eliminar
"elim"?

2017-06-04 00:49 UTC, radistmorse commented on Localization/localization.cfg
> +        precisemaneuver_utcontrol_timex10_tooltip       = Incremento por múltiplo de 10 veces
Again, this is the multiplier for UT specifically

2017-06-04 00:49 UTC, radistmorse commented on Localization/localization.cfg
> +        precisemaneuver_orbittools                      = Herramientas de órbitas
Way too long. Even "Herramientas" will be hard to fit

2017-06-04 00:49 UTC, radistmorse commented on Localization/localization.cfg
> +        precisemaneuver_orbittools_paste_tooltip        = Copiar maniobra del copiapapeles\n(puedes copiarla desde el modTransfer Window Planner)
space needed

2017-06-04 00:49 UTC, radistmorse commented on Localization/localization.cfg
> +        precisemaneuver_conics                          = Conos\nmodo de dibujo
The new line would be better after the second word. Makes lines more even.

2017-06-04 00:49 UTC, radistmorse commented on Localization/localization.cfg
> +        precisemaneuver_ejection_angle                  = Ángulo de Eyec.
mmm... really stretching the gui here... would "Áng. de Eyec." be good enough?

2017-06-04 00:49 UTC, radistmorse commented on Localization/localization.cfg
> +        precisemaneuver_mainmenu_keybindings            = Establecer atajos
I'd rather shorten this. "Estab. atajos" maybe? Or establ. I don't know the shortening rules in spanish.

2017-06-04 00:49 UTC, radistmorse commented on Localization/localization.cfg
> +        precisemaneuver_mainmenu_scale                  = Scala de la GUI
It's not like I absolutely need the capitals, but at least keep it consistent. All the other main menu labels are capitals.

2017-07-08 01:13 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_mainmenu_keybindings            = Establecer atajos
"Estab. atajos" is fine here

2017-07-08 01:27 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_keybindings_timex10             = Cambiar x10 veces
know what you mean but i can't think in a better translate here. For the moment

2017-07-08 01:37 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_pager_delete                    = Eliminar
The best here are "Eliminar" you could use "Elim". Is way difficult to find a 3 letters abbreviation here that is understandable. Probably "Supr" is the best way "Suprimir" is also a good translate  for "Delete"

2017-07-08 01:44 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_saver_save_as                   = Guardar como
mmmm no, not is the same. "Nuevo" is interpreted as "New"

2017-07-08 01:45 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_saver_delete                    = Eliminar
same as line 194

2017-07-08 01:46 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_utcontrol_timex10_tooltip       = Incremento por múltiplo de 10 veces
here is "Incrementa de a 10 veces"

2017-07-08 01:51 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_orbittools                      = Herramientas de órbitas
what about only "Herraminetas"

2017-07-08 01:56 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_ejection_angle                  = Ángulo de Eyec.
Do not abbreviate 2 words in a row, it can't be understood, here should be "Ángulo de Ejec." or "Áng de Eyección" I prefer the first one.

2017-07-08 01:59 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_conics                          = Conos\nmodo de dibujo
This translate is totally wrong should be "Modo de dibujo\n Orbital"

2017-07-08 02:04 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_module_gizmo                    = Gadget de Maniobra
gadget is also an english word, what's the meaning of gizmo in this case? i don't think we have a word for gizmo but maybe we can replace it with an spanish alternative

2017-07-08 02:09 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_module_patches                  = Control de parches
"patch" is not "parche" the correct translate here is "Control de trayectoria" :-)

2017-07-08 02:13 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_keybindings_normzero            = Anular normal
i'm not sure here whats mean "zero normal" in the UI, probably here should be "Cero normal"

2017-07-08 02:14 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_keybindings_radzero             = Anular radial
Same as line 163 "Cero radial" maybe?

2017-07-08 02:17 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_keybindings_patchesmore         = Mostrar más parches
here must be "Mostrar mas trayectorias"

2017-07-08 02:22 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_conics_more                     = Más parches
Parches is not the correct word. Should be "Mas trayectorias"

2017-07-08 02:28 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_conics_more_tooltip             = Mostrar más parches de conos en la vista de mapa
wrong again "Mostrar mas trayectorias en la vista mapa" or could be "Mostrar mas orbitas en la vista mapa"

2017-07-08 02:29 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_conics_less                     = Menos parches
"Menos trayectorias"

2017-07-08 02:30 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_conics_less_tooltip             = Mostrar menos parches de conos en la vista de mapa
"Mostrar menos trayectorias en la vista mapa" or "Mostrar menos orbitas en la vista mapa"

2017-07-08 02:37 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_conics_local_tooltip            = Mostrar parches relativos a los cuerpos celestiales
c'mon !! "Mostrar trayectorias relativas a los cuerpos celestes" or "Mostrar orbitas relativas a los cuerpos celestes"

2017-07-08 02:40 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_conics_SOI_entry_tooltip        = Mostrar parches relativos a la entrada de EDI
"Mostrar trayectorias relativas en la entrada de la esfera de influencia" or "Mostrar orbitas relativas en la entrada de la esfera de influencia"

2017-07-08 02:41 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_conics_SOI_exit_tooltip         = Mostrar parches relativos a la salida de EDI
"Mostrar trayectorias relativas en la salida de la esfera de influencia" or "Mostrar orbitas relativas en la salida de la esfera de influencia"

2017-07-08 02:43 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_conics_relative_tooltip         = Mostrar parches relativos al actual cuerpo celeste
"Mostrar trayectorias relativas al cuerpo celeste actual" or "Mostrar orbitas relativas al cuerpo celeste actual"

2017-07-08 02:44 UTC, Nemeko commented on Localization/localization.cfg
> +        precisemaneuver_conics_dynamic_tooltip          = Mostrar parches con cambios dinámicos
"Mostrar trayectorias con cambios dinamicos" or  "Mostrar orbitas con cambios dinamicos"

2018-03-09 11:35 UTC, closed without merging